---
  #- import_playbook: playbooks/pre-checks-hcp.yml
  #- import_playbook: playbooks/prepare.yml
  - import_playbook: playbooks/uninstall-bds.yml
  - import_playbook: playbooks/controller.yml
  - import_playbook: playbooks/gateway.yml
  - import_playbook: playbooks/k8s-hosts.yml
  - import_playbook: playbooks/k8s-cluster-lcm.yml
  #- import_playbook: playbooks/k8s-cluster-delete.yml
