---
  - name: Prepare gateway input file for epicctl.
    template:
      src: gateway.j2
      dest: /tmp/gateway.yml
      mode: 0640

  - name: Run epicctl command to setup and configure gateway node
    command: epicctl op -f /tmp/gateway.yml -n "OnPremSetup"
    register: res
    failed_when: res.rc != 0

  - debug:
      msg: "{{ res.stdout }}"
