---
  - name: Create k8s cluster.
    hosts: localhost
    gather_facts: false
    roles:
      - role: k8s-cluster
        vars:
          provision: yes
          addnode: no
          deletenode: no

